[package]
name = "procman"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.1"

# enable the async-await stuff using a feature flag:
# tokio = { version = "0.1", features = ["async-await-preview"] }
tokio = "0.1"
